### ISSUE TITLE
requirement of jq not included in clustermesh docs

### ISSUE THREAD

**Issue by sarob** [cilium/clustermesh-tools#5]
jq is not included in the clustermesh docs https://docs.cilium.io/en/stable/gettingstarted/external-workloads/#extract-the-tls-keys-for-external-workloads, so you get an error when running the extract-etcd-secrets.sh script. Not a huge deal, but some people may not realize that they just need to install jq.

**Comment by kaworu** [comment]
Hi @sarob and thanks for the report. I think the concern is valid, but this part of the documentation is being completely overhauled as part of the v1.10 release. /cc @tgraf

**Comment by sarob** [comment]
I have run into a bigger problem while configuring clustermesh during this step that requires a JSON parser. The shell script cannot dump the TLS certs.

I get a not found error. Is there a config map setting that needs to be added to allow the certs to be exposed and downloaded?


~ sean

**Comment by sarob** [comment]
I have run into a bigger problem while configuring clustermesh during this step that requires a JSON parser. The shell script cannot dump the TLS certs.

I get a not found error. Is there a config map setting that needs to be added to allow the certs to be exposed and downloaded?


~ sean

**Comment by kaworu** [comment]
> I get a not found error. Is there a config map setting that needs to be added to allow the certs to be exposed and downloaded

@sarob How did you install cilium?

Does the "not found error" happen when you run `extract-etcd-secrets.sh`? If that is the case, can you try `bash -x extract-etcd-secrets.sh` and paste the output here? Before posting please _review the content and edit out private information_ (such as keys) if any. The last line should be the one failing and it would hint at what k8s object is not found.
